apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: tekton-runner-main
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tekton-runner-main
    app.kubernetes.io/part-of: tekton-runner
  name: tekton-runner-main
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: tekton-runner-main
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: tekton-runner-main
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/tekton-runner/tekton-runner-main@sha256:fca15a5d7c68e7a4aec24847c4cc6a955ebafe57aa613339107391cce4a28ddd
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
