apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: tekton-runner-main
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tekton-runner-main
    app.kubernetes.io/part-of: tekton-runner
  name: tekton-runner-main
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: tekton-runner-main
status:
  loadBalancer: {}
