apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: tekton-runner-main
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tekton-runner-main
    app.kubernetes.io/part-of: tekton-runner
  name: tekton-runner-mainlxtk
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: tekton-runner-main
    weight: 100
status: {}
